[workspace]
members = ["server", "client"]

resolver = "2"

# ===== PROFILES =====

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 2

[profile.release]
opt-level = 3

[profile.release.package."*"]
opt-level = 3
